{{- if and .Values.aws.credentials.secretKey .Values.aws.credentials.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-ssm-secrets.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "kube-ssm-secrets.labels" . | nindent 4 }}
type: Opaque
data:
  credentials: {{ include "kube-ssm-secrets.aws-credentials" . | b64enc | quote }}
{{- end }}
